### ISSUE TITLE
question: how it works? 

### ISSUE THREAD

**Issue by Lvaskz** [TheAssassin/AppImageLauncherFS#3]
Hi there, I need to know how make it work?
You mean make it executable, I did it, is  not working for me.

**Comment by Lvaskz** [comment]
I tryied it in linuxmint 19 and ubuntu 18.04 nothing happens

**Comment by TheAssassin** [comment]
Define "does not work"... what did you make executable?

What do you expect to happen? What do you *think* it should do?

JFYI: This is not really production ready.

**Comment by Lvaskz** [comment]
Well, It is appimage, right? 
I make executable the appimage.
I tried it to integrate some appimages like appimagelauncher, I expect have the same result

**Comment by Lvaskz** [comment]
Ok, It is not ready.

**Comment by TheAssassin** [comment]
You _did_ read what AppImageLauncherFS is for? You're using it incorrectly. It's never been supposed to integrate anything.

**Comment by Lvaskz** [comment]
OK
